<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.itrys</groupId>
        <artifactId>ruoyi-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ruoyi-demo</artifactId>
    <packaging>jar</packaging>
    <description>
        demo模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-log</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-translation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-encrypt</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-push</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-mqtt</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
