<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.itrys</groupId>
        <artifactId>ruoyi-public-api</artifactId>
        <version>${revision}${changelist}</version>
    </parent>

    <artifactId>ruoyi-public-api-captcha</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-doc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-mail</artifactId>
        </dependency>
        <!-- 短信模块 -->
        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-sms</artifactId>
        </dependency>
        <!-- web服务 -->
        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-web</artifactId>
        </dependency>
        <!-- satoken -->
        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-satoken</artifactId>
        </dependency>

    </dependencies>
</project>
