<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.itrys</groupId>
        <artifactId>ruoyi-boot-starters</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ruoyi-boot-starter-social</artifactId>
    <packaging>jar</packaging>
    <description>
        ruoyi-boot-starter-social 授权认证
    </description>

    <dependencies>
        <dependency>
            <groupId>me.zhyd.oauth</groupId>
            <artifactId>JustAuth</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-json</artifactId>
        </dependency>

        <dependency>
            <groupId>org.itrys.boot</groupId>
            <artifactId>ruoyi-boot-starter-redis</artifactId>
        </dependency>
    </dependencies>
</project>
