<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.itrys</groupId>
        <artifactId>ruoyi-boot-starter-parent</artifactId>
        <version>${revision}</version>
    </parent>
    <groupId>org.itrys.boot</groupId>
    <artifactId>ruoyi-boot-starters</artifactId>
    <packaging>pom</packaging>

    <description>
        starters 通用模块
    </description>

    <modules>
        <module>ruoyi-boot</module>
        <module>ruoyi-common-social</module>
        <module>ruoyi-boot-starter-doc</module>
        <module>ruoyi-boot-starter-excel</module>
        <module>ruoyi-boot-starter-job</module>
        <module>ruoyi-boot-starter-log</module>
        <module>ruoyi-boot-starter-mail</module>
        <module>ruoyi-boot-starter-mybatis</module>
        <module>ruoyi-boot-starter-oss</module>
        <module>ruoyi-boot-starter-redis</module>
        <module>ruoyi-common-satoken</module>
        <module>ruoyi-common-security</module>
        <module>ruoyi-common-sms</module>
        <module>ruoyi-common-web</module>
        <module>ruoyi-common-translation</module>
        <module>ruoyi-common-sensitive</module>
        <module>ruoyi-boot-starter-json</module>
        <module>ruoyi-boot-starter-encrypt</module>
        <module>ruoyi-boot-starter-push</module>
        <module>ruoyi-boot-starter-mqtt</module>
    </modules>

</project>
